### ISSUE TITLE
Final report

### ISSUE THREAD

**Issue by mogyorosimartin** [Teaching-projects/SZE-MOSZE-2020-Insert_name_here#14]

**Comment by vizvezetek** [comment]
A féléves munkának és a leadott feladatnak megfelelően a megajánlott érdemjegyek a következő szerint alakultak a csapat számára:
- @bartaliszoltan  : 4
- @mogyorosimartin  : 3
- @dontrajik  : sajnos nem tudok megajánlani jegyet  a 0%-os github activity-re és a 0db commit/módosított kódsorra. 😔
